### ISSUE TITLE
`berkeley`: Fix type hint issue preventing Runtime from booting with Berkeley schema

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#578]
When I update `main.in` so that the `nmdc-schema` version is `11.0.0rc16` and then I run `make update-deps` and `make up-dev`, the FastAPI app fails to start up. Here's the error that appears in the container logs:

```py
2024-07-08 18:10:19 INFO:     Will watch for changes in these directories: ['/code']
2024-07-08 18:10:19 INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2024-07-08 18:10:19 INFO:     Started reloader process [1] using WatchFiles
2024-07-08 18:10:29 Process SpawnProcess-1:
2024-07-08 18:10:29 Traceback (most recent call last):
2024-07-08 18:10:29   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-07-08 18:10:29     self.run()
2024-07-08 18:10:29   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-07-08 18:10:29     self._target(*self._args, **self._kwargs)
2024-07-08 18:10:29   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
2024-07-08 18:10:29     target(sockets=sockets)
2024-07-08 18:10:29   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
2024-07-08 18:10:29     return asyncio.run(self.serve(sockets=sockets))
2024-07-08 18:10:29   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2024-07-08 18:10:29     return loop.run_until_complete(main)
2024-07-08 18:10:29   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-07-08 18:10:29   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
2024-07-08 18:10:29     await self._serve(sockets)
2024-07-08 18:10:29   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
2024-07-08 18:10:29     config.load()
2024-07-08 18:10:29   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
2024-07-08 18:10:29     self.loaded_app = import_from_string(self.app)
2024-07-08 18:10:29   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
2024-07-08 18:10:29     module = importlib.import_module(module_str)
2024-07-08 18:10:29   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-07-08 18:10:29     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-08 18:10:29   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-07-08 18:10:29   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-07-08 18:10:29   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-07-08 18:10:29   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-07-08 18:10:29   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-07-08 18:10:29   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-07-08 18:10:29   File "/code/nmdc_runtime/api/main.py", line 29, in <module>
2024-07-08 18:10:29     from nmdc_runtime.api.endpoints import (
2024-07-08 18:10:29   File "/code/nmdc_runtime/api/endpoints/metadata.py", line 29, in <module>
2024-07-08 18:10:29     from nmdc_runtime.site.repository import repo, run_config_frozen__normal_env
2024-07-08 18:10:29   File "/code/nmdc_runtime/site/repository.py", line 26, in <module>
2024-07-08 18:10:29     from nmdc_runtime.site.export.study_metadata import export_study_biosamples_metadata
2024-07-08 18:10:29   File "/code/nmdc_runtime/site/export/study_metadata.py", line 19, in <module>
2024-07-08 18:10:29     from nmdc_runtime.site.ops import add_output_run_event
2024-07-08 18:10:29   File "/code/nmdc_runtime/site/ops.py", line 77, in <module>
2024-07-08 18:10:29     from nmdc_runtime.site.translation.gold_translator import GoldStudyTranslator
2024-07-08 18:10:29   File "/code/nmdc_runtime/site/translation/gold_translator.py", line 9, in <module>
2024-07-08 18:10:29     class GoldStudyTranslator(Translator):
2024-07-08 18:10:29   File "/code/nmdc_runtime/site/translation/gold_translator.py", line 493, in GoldStudyTranslator
2024-07-08 18:10:29     ) -> nmdc.OmicsProcessing:
2024-07-08 18:10:29 AttributeError: module 'nmdc_schema.nmdc' has no attribute 'OmicsProcessing'
```

**Comment by eecavanna** [comment]
Fixed in the `berkeley` branch via PR #579
